# Narrowing data

Taking both (very large) data sets, reading files into Pandas, converting into DataFrames. Narrowing data to most relevant information.

In [158]:
#Dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

complete_aid_data=pd.read_csv("us_foreign_aid_complete.csv")

## Handling the USAID data

Drop all countries that are not classified as "Sub-Saharan Africa"; drop all NaN rows (these refer to sub-regions rather than countries). Set country name as index. Drop columns that refer to any entity by an ID# or acronym (redundant; left full name, which is clearest).

In [159]:
#Clean up the aid data
#Narrow to only Sub-Saharan African countries
subsaharan_africa_df = complete_aid_data.loc[complete_aid_data["region_name"]=="Sub-Saharan Africa", :]

#Remove NaN (refer to sub-regions rather than countries)
subsaharan_africa_df = subsaharan_africa_df.dropna(how="any")

#Set country_name as index
subsaharan_africa_df=subsaharan_africa_df.set_index("country_name")

concise_subsaharan_africa_df=subsaharan_africa_df.drop(
    ['country_id', 'country_code', 'region_id', 
       'income_group_id', 'income_group_acronym',
        'implementing_agency_acronym','implementing_subagency_id',
       'subagency_acronym', 'channel_category_id',
       'channel_subcategory_id', 'implementing_agency_id',
       'channel_subcategory_name', 'channel_id',
       'dac_category_id', 'dac_sector_code',
        'dac_purpose_code', 
       'funding_account_id', 'funding_agency_id',
       'funding_agency_acronym',
       'assistance_category_id',
       'aid_type_group_id',  'activity_id',
      'activity_project_number',  'transaction_type_id',
        'USG_sector_id', 'aid_type_group_name',
        'submission_id'], axis=1)

concise_subsaharan_africa_df.head()

,region_name,income_group_name,implementing_agency_name,subagency_name,channel_category_name,channel_name,dac_category_name,dac_sector_name,dac_purpose_name,funding_account_name,funding_agency_name,assistance_category_name,activity_name,activity_start_date,activity_end_date,transaction_type_name,fiscal_year,current_amount,constant_amount,USG_sector_name
country_name,,,,,,,,,,,,,,,,,,,,
South Sudan,Sub-Saharan Africa,Low Income Country,U.S. Agency for International Development,"Bureau for Democracy, Conflict and Humanitaria...",Multilateral,Multilateral - United Nations Organization Red...,Humanitarian,Emergency Response,Emergency food assistance,"Agency for International Development, Internat...",U.S. Agency for International Development,Economic,Title II - WFP,4/10/2016,12/31/2018,Obligations,2017,206430000,206430000,"Protection, Assistance and Solutions"
Nigeria,Sub-Saharan Africa,Lower Middle Income Country,U.S. Agency for International Development,"Bureau for Democracy, Conflict and Humanitaria...",Multilateral,World Food Program,Humanitarian,Emergency Response,Emergency food assistance,"Agency for International Development, Internat...",U.S. Agency for International Development,Economic,World Food Programme - Regional Emergency Oper...,12/12/2016,6/30/2018,Obligations,2017,154700000,154700000,"Protection, Assistance and Solutions"
Kenya,Sub-Saharan Africa,Lower Middle Income Country,U.S. Agency for International Development,Bureau for Africa,Government,Government of Kenya,Health and Population,HIV/AIDS,STD control including HIV/AIDS,"Department of State, Global Health Programs",Department of State,Economic,KEMSA Medical Commodities Project (MCP),9/25/2015,9/24/2020,Obligations,2017,152795617,152795617,HIV/AIDS
Kenya,Sub-Saharan Africa,Lower Middle Income Country,U.S. Agency for International Development,Bureau for Africa,Enterprises,"Chemonics International, Inc.",Health and Population,HIV/AIDS,STD control including HIV/AIDS,"Department of State, Global Health Programs",Department of State,Economic,Kenya Pharmaceutical Program,7/6/2009,9/30/2015,Obligations,2011,138050000,151569324,HIV/AIDS
Botswana,Sub-Saharan Africa,Upper Middle Income Country,U.S. Agency for International Development,Bureau for Global Health,NGO,Partnership for Supply Chain Management,Health and Population,HIV/AIDS,STD control including HIV/AIDS,"Agency for International Development, HIV/AIDS...",U.S. Agency for International Development,Economic,Supply Chain Management System (SCMS),9/27/2005,2/28/2017,Obligations,2008,130317448,148985076,HIV/AIDS

## Narrow more

Left only country name and income group, organization category, aid category, and current and constant amounts.

In [160]:

concise_subsaharan_africa_df.columns
#Narrow more

abridged_subsaharan_africa_df=concise_subsaharan_africa_df.drop(
    ['region_name', 'implementing_agency_name',
    'subagency_name', 'channel_category_name', 'channel_name',
    'dac_sector_name', 'dac_purpose_name',
    'funding_account_name', 'funding_agency_name', 'activity_name', 'activity_start_date',
    'activity_end_date', 'transaction_type_name', 'USG_sector_name'], axis=1)

abridged_subsaharan_africa_df.head()

,income_group_name,dac_category_name,assistance_category_name,fiscal_year,current_amount,constant_amount
country_name,,,,,,
South Sudan,Low Income Country,Humanitarian,Economic,2017,206430000,206430000
Nigeria,Lower Middle Income Country,Humanitarian,Economic,2017,154700000,154700000
Kenya,Lower Middle Income Country,Health and Population,Economic,2017,152795617,152795617
Kenya,Lower Middle Income Country,Health and Population,Economic,2011,138050000,151569324
Botswana,Upper Middle Income Country,Health and Population,Economic,2008,130317448,148985076

## Grouped version of abridged DataFrame

Grouped the DataFrame by country and year. Ran a sum for both current and constant amount.

In [161]:
grp_abgd_ssa_df=abridged_subsaharan_africa_df.groupby(["fiscal_year", "country_name"])
grp_abgd_ssa_df["current_amount", "constant_amount"].sum().head(38)

                              current_amount  constant_amount
fiscal_year country_name
2002        Angola                    134343           179097
            Benin                     299248           398938
            Congo (Kinshasa)           96936           129229
            Ethiopia                  326499           435267
            Ghana                     829031          1105211
            Guinea                    150000           199971
            Kenya                      54069            72082
            Liberia                   705354           940332
            Madagascar                196000           261295
            Malawi                     68330            91093
            Mali                      255896           341144
            Mozambique                469057           625318
            Namibia                   336351           448402
            Nigeria                   392583           523368
            Rwanda                    218342           291079
            Senegal                   100000           133314
            South Africa              316797           422333
            Uganda                       185              246
            Zimbabwe                   80552           107389
2003        Angola                    190276           248908
            Benin                     126008           164836
            Congo (Kinshasa)          100187           131059
            Ethiopia                  132391           173185
            Ghana                     322032           421262
            Guinea                    150000           196221
            Kenya                     166459           217751
            Liberia                   220363           288265
            Madagascar                714495           934658
            Mali                      222879           291557
            Mozambique                747208           977450
            Nigeria                   195589           255860
            Rwanda                    319169           417516
            Senegal                   180475           236086
            Sierra Leone               91300           119433
            Somalia                   150000           196221
            South Africa              968751          1267259
            Uganda                      -563             -736
            Zimbabwe                  271351           354965

## Deal with WGI Data

Created a new Excel file with only the data for stability and violence (removed rows at top to eliminate the key; it was not relevant). Read Excel file into Jupyter Notebook; printed as DF.

In [162]:
wgi_full_data=pd.read_excel("WGI_data_full.xlsx")

In [163]:
wgi_full_data.head()

,Unnamed: 0,Unnamed: 1,1996,1996.1,1996.2,1996.3,1996.4,1996.5,1998,1998.1,...,2016.2,2016.3,2016.4,2016.5,2017,2017.1,2017.2,2017.3,2017.4,2017.5
0,Country/Territory,WBCode,Estimate,StdErr,NumSrc,Rank,Lower,Upper,Estimate,StdErr,...,NumSrc,Rank,Lower,Upper,Estimate,StdErr,NumSrc,Rank,Lower,Upper
1,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3,94.2857,75.7143,99.5238,1.31865,0.24894,3,95.2381,79.0476,99.5238
2,Andorra,ADO,1.17016,0.613507,1,89.3617,52.1277,100,1.18364,0.575733,...,2,97.1429,79.0476,99.5238,1.44971,0.300801,2,97.619,80.4762,100
3,Afghanistan,AFG,-2.41404,0.475315,2,2.12766,0,6.91489,-2.423,0.435324,...,6,0.952381,0,3.33333,-2.78077,0.223473,6,0.47619,0,1.42857
4,Angola,AGO,-2.05729,0.373857,4,3.7234,0,9.04255,-2.31307,0.345463,...,6,33.3333,21.9048,48.0952,-0.294626,0.220516,6,34.2857,22.381,49.0476

## Narrow by country

Used a .loc to return only countries that are Sub-Saharan. (I have for the time being included every country that is part of the "Sub-Saharan Africa" region in the USAID data.)

In [164]:
wgi_full_data.head()
wgi_full_data.columns
subsaharan_africa_wgi_data = wgi_full_data.loc[(wgi_full_data["Unnamed: 0"]=="Angola")|(wgi_full_data["Unnamed: 0"]=="Benin")|(wgi_full_data["Unnamed: 0"]=="Burundi")|
                                               (wgi_full_data["Unnamed: 0"]=="Congo (Kinshasa)")|(wgi_full_data["Unnamed: 0"]=="Ethiopia")|(wgi_full_data["Unnamed: 0"]=="Ghana")|
                                               (wgi_full_data["Unnamed: 0"]=="Kenya")|(wgi_full_data["Unnamed: 0"]=="Madagascar")|(wgi_full_data["Unnamed: 0"]=="Mali")|
                                               (wgi_full_data["Unnamed: 0"]=="Mozambique")|(wgi_full_data["Unnamed: 0"]=="Namibia")|(wgi_full_data["Unnamed: 0"]=="Nigeria")|
                                               (wgi_full_data["Unnamed: 0"]=="Rwanda")|(wgi_full_data["Unnamed: 0"]=="Senegal")|(wgi_full_data["Unnamed: 0"]=="Sierra Leone")|
                                               (wgi_full_data["Unnamed: 0"]=="Somalia")|(wgi_full_data["Unnamed: 0"]=="South Africa")|(wgi_full_data["Unnamed: 0"]=="Uganda")|
                                               (wgi_full_data["Unnamed: 0"]=="Zimbabwe"),:]

#Fix first two column names to make them understandable. (Will fix others after dropping out-of-range columns. )
subsaharan_africa_wgi_data=subsaharan_africa_wgi_data.rename(columns={"Unnamed: 0": "Country", "Unnamed: 1": "Country Abbreviation"})

subsaharan_africa_wgi_data.head()

,Country,Country Abbreviation,1996,1996.1,1996.2,1996.3,1996.4,1996.5,1998,1998.1,...,2016.2,2016.3,2016.4,2016.5,2017,2017.1,2017.2,2017.3,2017.4,2017.5
4,Angola,AGO,-2.05729,0.373857,4,3.7234,0,9.04255,-2.31307,0.345463,...,6,33.3333,21.9048,48.0952,-0.294626,0.220516,6,34.2857,22.381,49.0476
16,Burundi,BDI,-2.1139,0.475315,2,3.19149,0,9.04255,-2.29334,0.435324,...,6,5.71429,2.85714,8.57143,-1.97038,0.225936,6,4.7619,1.90476,8.09524
18,Benin,BEN,1.04893,0.475315,2,84.5745,56.9149,100,0.741325,0.435324,...,6,47.1429,32.381,58.5714,0.0453255,0.225936,6,48.0952,32.8571,62.381
63,Ethiopia,ETH,-1.05112,0.373857,4,16.4894,6.38298,31.9149,-0.630291,0.345463,...,8,7.61905,5.71429,10.4762,-1.68741,0.212268,8,7.61905,3.80952,9.52381
71,Ghana,GHA,-0.233099,0.373857,4,38.2979,20.7447,59.5745,-0.135467,0.345463,...,8,40.9524,27.619,53.3333,0.0864814,0.212268,8,49.5238,35.7143,63.3333

## Possible way to quantify stability (1)

This shows the percentile within which each country fell a given year. (Note: I have trimmed the number of years to only those for which we have data from USAID.) One benefit of using percentiles is that we can bin the data by percentile using the same method that the WGI uses. We could then look at whether a country stays at the same level (i.e. stays in the bottom 10% or moves up). I'm not sure whether this would be an oversimplification.

In [165]:
subsaharan_africa_wgi_rank=subsaharan_africa_wgi_data.loc[:,["Country", "2001.3" "2002.3", 
                                                            "2003.3", "2004.3", 
                                                            "2005.3", "2006.3", 
                                                            "2007.3", "2008.3", 
                                                            "2009.3", "2010.3", 
                                                            "2011.3", "2012.3", 
                                                            "2013.3", "2014.3", 
                                                            "2015.3", "2016.3", 
                                                            "2017.3"]]
subsaharan_africa_wgi_rank.head()
#Will add % formatting later. Will fix headers later.

,Country,2001.32002.3,2003.3,2004.3,2005.3,2006.3,2007.3,2008.3,2009.3,2010.3,2011.3,2012.3,2013.3,2014.3,2015.3,2016.3,2017.3
4,Angola,NaN,19.598,16.5049,21.3592,27.5362,24.1546,31.25,32.7014,37.9147,34.5972,35.0711,35.0711,32.8571,28.0952,33.3333,34.2857
16,Burundi,NaN,1.50754,0.970874,6.79612,9.17874,9.66184,9.13461,12.7962,6.63507,4.73934,5.6872,8.53081,20.4762,5.71429,5.71429,4.7619
18,Benin,NaN,69.3467,54.3689,59.7087,63.285,57.971,56.7308,60.1896,53.5545,57.346,58.2938,58.2938,47.1429,45.2381,47.1429,48.0952
63,Ethiopia,NaN,10.0503,11.6505,5.82524,7.24638,6.76329,8.65385,6.63507,5.6872,6.16114,7.109,8.05687,8.57143,8.09524,7.61905,7.61905
71,Ghana,NaN,42.2111,47.0874,51.9417,46.3768,40.5797,43.75,45.4976,46.9194,52.6066,50.7109,47.8673,41.4286,44.2857,40.9524,49.5238

## Possible way to quantify stability (2)

This is by score. (Range is -2.5 to 2.5, with higher scores being better.) Perhaps more precise if changes are relatively small.

In [166]:
subsaharan_africa_wgi_score=subsaharan_africa_wgi_data.loc[:,["Country", 2002, 
                                                            2003, 2004,
                                                            2005, 2006,  
                                                            2007, 2008,  
                                                            2009, 2010,  
                                                            2011, 2012,
                                                            2013, 2014, 
                                                            2015, 2016, 
                                                            2017]]
subsaharan_africa_wgi_score.head()

,Country,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
4,Angola,-1.57705,-1.00654,-1.0628,-0.887544,-0.541986,-0.666032,-0.362911,-0.347262,-0.226182,-0.369238,-0.389323,-0.391233,-0.333232,-0.500898,-0.315899,-0.294626
16,Burundi,-2.28824,-2.24453,-2.52378,-1.52474,-1.42701,-1.37533,-1.63816,-1.27269,-1.62596,-1.8072,-1.70474,-1.35028,-0.784407,-1.93951,-1.97072,-1.97038
18,Benin,0.820294,0.679063,0.265107,0.446816,0.54701,0.386123,0.374591,0.403298,0.26126,0.318356,0.364368,0.301189,0.0271398,-0.013514,-0.00202717,0.0453255
63,Ethiopia,-1.22321,-1.40855,-1.31148,-1.69075,-1.73894,-1.80341,-1.73009,-1.64079,-1.6351,-1.50696,-1.56427,-1.40731,-1.33939,-1.49819,-1.61981,-1.68741
71,Ghana,-0.163768,0.0287742,0.0399668,0.168321,0.00803204,-0.0717858,-0.0276288,0.0299434,0.0260932,0.167112,0.130695,0.0606061,-0.106808,-0.0320993,-0.130929,0.0864814